### Agenda

* How TensorFlow Works
* Declaring Variables and Tensors
* Using Placeholders and Variables
* Working with Matrices
* Declaring Operations
* Implementing Activation Functions

#### How TensorFlow Works
* Declaring Tensors
* Basic Unit of TensorFlow

In [1]:
import tensorflow as tf

In [31]:
tf.__version__

'1.15.0'

In [2]:
##Fixed tensos
zero_tsr = tf.zeros([4,5])

In [3]:
zero_tsr

<tf.Tensor 'zeros:0' shape=(4, 5) dtype=float32>

In [4]:
ones_tsr = tf.ones([6,7])

In [5]:
ones_tsr

<tf.Tensor 'ones:0' shape=(6, 7) dtype=float32>

In [6]:
filled_tsr = tf.fill([3,4],99)  ##Create a tensor filled with scalar values

In [7]:
filled_tsr

<tf.Tensor 'Fill:0' shape=(3, 4) dtype=int32>

In [8]:
constant_tsr = tf.constant([1,2,3])

In [9]:
constant_tsr

<tf.Tensor 'Const:0' shape=(3,) dtype=int32>

In [10]:
tf.constant(-1.0 , shape = [2,3])  ###Constant 2-D tensor populated with scalar value -1.

<tf.Tensor 'Const_1:0' shape=(2, 3) dtype=float32>

In [11]:
# Tensors of similar shape
zero_similar = tf.zeros_like(constant_tsr)   ###Create a tensor with all elements set to zero 
zero_similar

<tf.Tensor 'zeros_like:0' shape=(3,) dtype=int32>

#### Sequence tensors

In [12]:
linear_tsr = tf.linspace(start=0.0, stop=1.0, num=3)

In [13]:
linear_tsr


<tf.Tensor 'LinSpace:0' shape=(3,) dtype=float32>

In [14]:
int_seq_rng = tf.range(start=6, limit=15, delta=3)

In [15]:
int_seq_rng

<tf.Tensor 'range:0' shape=(3,) dtype=int32>

#### Random tensors

In [17]:
rand_tsr = tf.random_uniform([3,4],minval= 0 ,maxval=1)

In [18]:
rand_tsr

<tf.Tensor 'random_uniform:0' shape=(3, 4) dtype=float32>

In [19]:
tf.random_shuffle(rand_tsr)   ###Randomly shuffles tensor along first dimension

<tf.Tensor 'RandomShuffle:0' shape=(3, 4) dtype=float32>

In [20]:
tf.random_crop(rand_tsr,[2,2])  ###3Randomly crops a tensor to given shape

<tf.Tensor 'random_crop:0' shape=(2, 2) dtype=float32>

#### Using Placeholders & Variables

A placeholder is simply a variable that we will assign data to at a later date.

In [21]:
my_var = tf.Variable(tf.zeros([2,3]))
#Variable function takes tensor as an input & outputs a variable

In [23]:
my_var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32_ref>

In [24]:
sess = tf.Session()

In [25]:
sess.run(ones_tsr)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

In [27]:
sess.run(zero_tsr)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

In [28]:
sess.run(constant_tsr)

array([1, 2, 3])

In [29]:
sess.run(filled_tsr)

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])

In [30]:
sess.run(rand_tsr)

array([[5.0796902e-01, 8.5012960e-01, 9.0699577e-01, 4.2532682e-01],
       [6.9180942e-01, 8.0373740e-01, 1.6240680e-01, 4.6396255e-04],
       [8.6893725e-01, 3.4096241e-03, 5.1981020e-01, 2.6279211e-02]],
      dtype=float32)

In [32]:
a = sess.run(my_var.initializer)

In [35]:
tfops = tf.global_variables_initializer()

In [36]:
sess.run(tfops)

In [37]:
x = tf.placeholder(tf.float32, shape=[2,2])  

In [41]:
x

<tf.Tensor 'Placeholder:0' shape=(2, 2) dtype=float32>

In [39]:
y = tf.identity(x)

In [42]:
y

<tf.Tensor 'Identity:0' shape=(2, 2) dtype=float32>

In [44]:
import numpy as np
x_vals = np.random.rand(2,2)

In [46]:
sess= tf.Session()

In [47]:
sess.run(y, feed_dict={x:x_vals})

array([[0.5532293 , 0.07875539],
       [0.34028712, 0.5513105 ]], dtype=float32)

In [48]:
y_1 = tf.square(x)

In [49]:
sess.run(y_1 , feed_dict ={x:x_vals})

array([[0.30606264, 0.00620241],
       [0.11579532, 0.30394325]], dtype=float32)

In [50]:
### Variable
sess = tf.Session()
first_var = tf.Variable(tf.zeros([2,3]))

In [51]:
sess.run(first_var.initializer)

In [52]:
second_var  = tf.Variable(tf.zeros_like(first_var))

In [53]:
sess.run(second_var.initializer)

In [54]:
# tf.constant() - creats a "constant" op. It takes a single value & output same value to nodes directly connected.
a = tf.constant(5, name="input_a")
b = tf.constant(3, name="input_b")

In [56]:
a  ###no value as graph is not run as of now

<tf.Tensor 'input_a:0' shape=() dtype=int32>

In [57]:
c = tf.multiply(a,b, name="mul_c")
d = tf.add(a,b, name="add_d")
e = tf.add(c,d, name="add_e")

In [58]:
sess  = tf.Session()

In [59]:
sess.run(e)

23

In [60]:
sess.run(a)

5

In [61]:
##Now, instead of scalar values, we will try vector

In [62]:
a = tf.constant([5,3], name="input_a") #vector creation

In [63]:
b = tf.reduce_prod(a, name="prob_b")  ###Multiply elements

In [65]:
sess.run(b)

15

In [66]:
c = tf.reduce_sum(a, name="sum_c")

In [67]:
d = tf.add(b,c,name="add_d")

In [68]:
sess.run(c)

8

In [69]:
sess.run(d)

23

In [70]:
#Feeding numpy to tensorflow
import numpy as np

In [71]:
np_a = np.array([3,4])
np_b = np.array([5,6])

In [74]:
add_nps = tf.add(np_a , np_b , 'my_add')

In [75]:
sess.run(add_nps)  

array([ 8, 10])

#### Having multiple sessions


In [76]:
g = tf.Graph()

In [77]:
#Create new graphs
g1 = tf.Graph()
g2 = tf.Graph()

In [78]:
with g1.as_default():
    a = tf.constant(15, name="input_a")
    b = tf.constant(13, name="input_b")
    c = tf.add(a,b)

In [79]:
sess=tf.Session(graph=g1)

In [80]:
e = sess.run(c)

In [82]:
with g2.as_default():
    a = tf.constant(25, name="input_a")
    b = tf.constant(23, name="input_b")
    c = tf.add(a,b)

In [83]:
sess = tf.Session(graph = g2)

In [85]:
f = sess.run(c)
f

48

In [86]:
sess.run([a,b])

[25, 23]

In [87]:
#Creating Variables
my_var = tf.Variable(3,name="my_var")

In [89]:
add = tf.add(5,my_var)

In [90]:
mul = tf.multiply(6,my_var)

In [91]:
e = tf.add(add,mul)

In [93]:
init = tf.global_variables_initializer()

In [95]:
sess = tf.Session()

In [96]:
sess.run(init)

In [97]:
var1 = tf.Variable(0, name="initialize_me")
var2 = tf.Variable(1, name="no_initialization")
init = tf.variables_initializer([var1], name="init_var1")
sess = tf.Session()


In [99]:
# Create variable with starting value of 1
my_var = tf.Variable(1)

In [101]:
# Create an operation that multiplies the variable by 2 each time it is run
#to change value of variable, use .assign function
my_var_times_two = my_var.assign(my_var * 2)

In [102]:

# Initialization operation
init = tf.global_variables_initializer()

In [103]:
# Start a session
sess = tf.Session()

In [104]:
# Start a session
sess = tf.Session()

In [105]:

# Initialize variable
sess.run(init)

In [106]:
sess.run(my_var_times_two)

2

In [107]:
sess.run(my_var_times_two)

4

In [108]:
sess.run(my_var_times_two)

8

In [109]:
sess.run(my_var.assign_add(1))

9

In [110]:
sess.run(my_var.assign_add(1))

10